name: Bug Report
description: Report a bug in the project
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report."
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug you encountered.
      placeholder: "Tell us what you see!"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Detail the steps taken to encounter the bug.
      placeholder: "1. Do this... 2. Then do this... 3. And then you see..."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: Please confirm the following
      options:
        - label: I have searched the existing issues
          required: true
