name: Documentation Improvement
description: Suggest improvements or report issues in the documentation
title: '[DOCS]: '
labels: ['documentation']
assignees: ''

body:
  - type: markdown
    attributes:
      value: "📚 Thanks for taking the time to improve our documentation!"

  - type: textarea
    id: documentation-location
    attributes:
      label: Documentation Location
      description: Please provide a link to the documentation page or a clear description of where the documentation lives.
      placeholder: "URL or description of the documentation's location."
    validations:
      required: true

  - type: textarea
    id: current-docs
    attributes:
      label: Current State of the Documentation
      description: Describe the current state of the documentation and why it is insufficient or incorrect.
      placeholder: "What is currently in the documentation that needs improvement?"
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: Suggest how we can improve the documentation. Be as detailed as possible.
      placeholder: "Your detailed suggestion on how to improve the documentation..."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional context that might be helpful, like how the issue affects your use of the project, etc.
      placeholder: "Any additional information or context about the documentation issue."

  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: Confirm before submission
      options:
        - label: I confirm that this feedback is accurate to the best of my knowledge and that I have searched for existing similar requests.
          required: true
