name: Security Vulnerability
description: Report a security vulnerability in the project
title: '[SECURITY]: '
labels: ['security']
assignees: 
  - 'chismaeel'

body:
  - type: markdown
    attributes:
      value: "⚠️ **Please report security vulnerabilities through our responsible disclosure process.** Only use this form if you are unable to use our standard reporting channels."

  - type: markdown
    attributes:
      value: "🔒 Security reports are handled with the highest priority and sensitivity. Your report will be confidential and only shared with project maintainers."

  - type: textarea
    id: vulnerability-summary
    attributes:
      label: Vulnerability Summary
      description: Provide a general summary of the vulnerability.
      placeholder: "A brief description of the security issue."
    validations:
      required: true

  - type: textarea
    id: potential-impact
    attributes:
      label: Potential Impact
      description: Describe the potential impact of this vulnerability.
      placeholder: "What could happen if this vulnerability is exploited?"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: "Details about your environment in which the vulnerability was discovered (e.g., version of the software, operating system)."
      placeholder: "e.g., Project version 1.2.3, Windows 10"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: If possible, provide steps to reproduce the vulnerability.
      placeholder: "Steps to reproduce the vulnerability..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context or information about the vulnerability or its discovery.
      placeholder: "Any additional information about the security issue."

  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: Confirm before submission
      options:
        - label: I understand that this information will be kept confidential and only shared with project maintainers.
          required: true
